CREATE TYPE IF NOT EXISTS stateGame AS ENUM ('CREATED', 'STARTED', 'ENDED');

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  ip text NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_connection TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS host (
  id SERIAL PRIMARY KEY,
  ip text NOT NULL,
  name text NOT NULL,
  nb_players integer NOT NULL,
  state stateGame DEFAULT 'CREATED',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);