CREATE TYPE stateGame AS ENUM ('CREATED', 'STARTED', 'ENDED', 'UNKNOWN');
ALTER TYPE public.stateGame RENAME TO host_state_enum;

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  ip text NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_connection TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS host (
  id SERIAL PRIMARY KEY,
  ip text NOT NULL,
  name text NOT NULL,
  nb_players integer NOT NULL,
  state host_state_enum DEFAULT 'CREATED',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
