name: Docker Image CI

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check branch name
      id: check_branch
      run: echo "::set-output name=branch::${{ github.ref }}"

    - name: Debug branch name
      run: echo "Branch name is ${{ steps.check_branch.outputs.branch }}"

    - name: Build and push Docker image for dev branch
      if: steps.check_branch.outputs.branch == 'refs/heads/dev'
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker build -t ghcr.io/Operation-Strike-Secure/backend:dev .
        docker push ghcr.io/Operation-Strike-Secure/backend:dev
        tag=$(date +%s)
        docker build -t ghcr.io/Operation-Strike-Secure/backend:${tag} .
        docker push ghcr.io/Operation-Strike-Secure/backend:${tag}

    - name: Build and push Docker image for main branch
      if: steps.check_branch.outputs.branch == 'refs/heads/main'
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker build -t ghcr.io/Operation-Strike-Secure/backend:main .
        docker push ghcr.io/Operation-Strike-Secure/backend:main
        docker build -t ghcr.io/Operation-Strike-Secure/backend:latest .
        docker push ghcr.io/Operation-Strike-Secure/backend:latest